name: VFS Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      TARGET_URL: "https://www.digikey.com/en/maker/projects/realtime-gps-tracker-with-raspberry-pi-pico-sim800l-gsm-module/d133a048a1ef4f40bb14e3be15be7467?utm_campaign=real-time_gps_tracker_wit&utm_content=digikey&utm_medium=social&utm_source=twitter"
      CHECK_TEXT: "Project Overview"

    steps:
      - name: Repo'yu çek
        uses: actions/checkout@v4

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: requests kur
        run: pip install requests

      - name: Botu çalıştır
        run: python bot.py
